# This file was generated by GoReleaser. DO NOT EDIT.
cask "zerolint" do
  desc "zerolint is a Go static analysis tool (linter) that detects unnecessary or potentially incorrect usage of pointers to zero-sized types."
  homepage "https://github.com/fillmore-labs/zerolint"
  version "0.0.11"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zerolint"
  depends_on formula: [
      "go",
    ]

  on_macos do
    on_intel do
      url "https://github.com/eikemeier/zerolint/releases/download/v0.0.11/zerolint_darwin_amd64"
      sha256 "0301dd940b3985bb79ea139aa01330f97c54b5dec396ed82c1c7748948e6bba9"
    end
    on_arm do
      url "https://github.com/eikemeier/zerolint/releases/download/v0.0.11/zerolint_darwin_arm64"
      sha256 "2fd98e76cbe403161fef014917247e9ae4ce4dcee50eba10551048812ca27201"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/eikemeier/zerolint/releases/download/v0.0.11/zerolint_linux_amd64"
      sha256 "01bd768b761615de87d265d0b881e24f31ac09a3fb065aa980ac1e4e3af15614"
    end
    on_arm do
      url "https://github.com/eikemeier/zerolint/releases/download/v0.0.11/zerolint_linux_arm64"
      sha256 "68d629b311241a00f8507dec4d244b51546d17f91240a7d31e91d9d52c20eddb"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "#{staged_path}/zerolint"]
    end
  end

  # No zap stanza required
end
